import React from "react"

export default {
  name: "sale",
  type: "document",
  title: "Sale",
  icon: () => (
    <svg
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"></path>
    </svg>
  ),
  fields: [
    {
      name: "active",
      type: "boolean",
      title: "Active",
      description: "The current status of the sale",
      initialValue: true
    },
    {
      name: "name",
      type: "string",
      title: "Name",
      description: "The name of the sale",
      validation: (Rule) => Rule.required()
    },
    {
      name: "logo",
      type: "image",
      title: "Logo",
      description:
        "A logo that can help people differentiate your sale from others",
      validation: (Rule) => Rule.required()
    },
    {
      name: "description",
      type: "text",
      title: "Description",
      description: "A description of your sale",
      validation: (Rule) => Rule.required()
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      description:
        "A slug that will appear at the end of the sale URL to identify it",
      options: {
        source: "name",
        maxLength: 96
      },
      validation: (Rule) => Rule.required()
    },
    {
      name: "currency",
      type: "string",
      title: "Currency",
      description: "The currency that will be used for this sale",
      options: {
        list: [
          { title: "AFN", value: "AFN" },
          { title: "EUR", value: "EUR" },
          { title: "ALL", value: "ALL" },
          { title: "DZD", value: "DZD" },
          { title: "USD", value: "USD" },
          { title: "AOA", value: "AOA" },
          { title: "XCD", value: "XCD" },
          { title: "ARS", value: "ARS" },
          { title: "AMD", value: "AMD" },
          { title: "AWG", value: "AWG" },
          { title: "AUD", value: "AUD" },
          { title: "AZN", value: "AZN" },
          { title: "BSD", value: "BSD" },
          { title: "BHD", value: "BHD" },
          { title: "BDT", value: "BDT" },
          { title: "BBD", value: "BBD" },
          { title: "BYN", value: "BYN" },
          { title: "BZD", value: "BZD" },
          { title: "XOF", value: "XOF" },
          { title: "BMD", value: "BMD" },
          { title: "INR", value: "INR" },
          { title: "BTN", value: "BTN" },
          { title: "BOB", value: "BOB" },
          { title: "BOV", value: "BOV" },
          { title: "BAM", value: "BAM" },
          { title: "BWP", value: "BWP" },
          { title: "NOK", value: "NOK" },
          { title: "BRL", value: "BRL" },
          { title: "BND", value: "BND" },
          { title: "BGN", value: "BGN" },
          { title: "BIF", value: "BIF" },
          { title: "CVE", value: "CVE" },
          { title: "KHR", value: "KHR" },
          { title: "XAF", value: "XAF" },
          { title: "CAD", value: "CAD" },
          { title: "KYD", value: "KYD" },
          { title: "CLP", value: "CLP" },
          { title: "CLF", value: "CLF" },
          { title: "CNY", value: "CNY" },
          { title: "COP", value: "COP" },
          { title: "COU", value: "COU" },
          { title: "KMF", value: "KMF" },
          { title: "CDF", value: "CDF" },
          { title: "NZD", value: "NZD" },
          { title: "CRC", value: "CRC" },
          { title: "HRK", value: "HRK" },
          { title: "CUP", value: "CUP" },
          { title: "CUC", value: "CUC" },
          { title: "ANG", value: "ANG" },
          { title: "CZK", value: "CZK" },
          { title: "DKK", value: "DKK" },
          { title: "DJF", value: "DJF" },
          { title: "DOP", value: "DOP" },
          { title: "EGP", value: "EGP" },
          { title: "SVC", value: "SVC" },
          { title: "ERN", value: "ERN" },
          { title: "ETB", value: "ETB" },
          { title: "FKP", value: "FKP" },
          { title: "FJD", value: "FJD" },
          { title: "XPF", value: "XPF" },
          { title: "GMD", value: "GMD" },
          { title: "GEL", value: "GEL" },
          { title: "GHS", value: "GHS" },
          { title: "GIP", value: "GIP" },
          { title: "GTQ", value: "GTQ" },
          { title: "GBP", value: "GBP" },
          { title: "GNF", value: "GNF" },
          { title: "GYD", value: "GYD" },
          { title: "HTG", value: "HTG" },
          { title: "HNL", value: "HNL" },
          { title: "HKD", value: "HKD" },
          { title: "HUF", value: "HUF" },
          { title: "ISK", value: "ISK" },
          { title: "IDR", value: "IDR" },
          { title: "XDR", value: "XDR" },
          { title: "IRR", value: "IRR" },
          { title: "IQD", value: "IQD" },
          { title: "ILS", value: "ILS" },
          { title: "JMD", value: "JMD" },
          { title: "JPY", value: "JPY" },
          { title: "JOD", value: "JOD" },
          { title: "KZT", value: "KZT" },
          { title: "KES", value: "KES" },
          { title: "KPW", value: "KPW" },
          { title: "KRW", value: "KRW" },
          { title: "KWD", value: "KWD" },
          { title: "KGS", value: "KGS" },
          { title: "LAK", value: "LAK" },
          { title: "LBP", value: "LBP" },
          { title: "LSL", value: "LSL" },
          { title: "ZAR", value: "ZAR" },
          { title: "LRD", value: "LRD" },
          { title: "LYD", value: "LYD" },
          { title: "CHF", value: "CHF" },
          { title: "MOP", value: "MOP" },
          { title: "MKD", value: "MKD" },
          { title: "MGA", value: "MGA" },
          { title: "MWK", value: "MWK" },
          { title: "MYR", value: "MYR" },
          { title: "MVR", value: "MVR" },
          { title: "MRU", value: "MRU" },
          { title: "MUR", value: "MUR" },
          { title: "XUA", value: "XUA" },
          { title: "MXN", value: "MXN" },
          { title: "MXV", value: "MXV" },
          { title: "MDL", value: "MDL" },
          { title: "MNT", value: "MNT" },
          { title: "MAD", value: "MAD" },
          { title: "MZN", value: "MZN" },
          { title: "MMK", value: "MMK" },
          { title: "NAD", value: "NAD" },
          { title: "NPR", value: "NPR" },
          { title: "NIO", value: "NIO" },
          { title: "NGN", value: "NGN" },
          { title: "OMR", value: "OMR" },
          { title: "PKR", value: "PKR" },
          { title: "PAB", value: "PAB" },
          { title: "PGK", value: "PGK" },
          { title: "PYG", value: "PYG" },
          { title: "PEN", value: "PEN" },
          { title: "PHP", value: "PHP" },
          { title: "PLN", value: "PLN" },
          { title: "QAR", value: "QAR" },
          { title: "RON", value: "RON" },
          { title: "RUB", value: "RUB" },
          { title: "RWF", value: "RWF" },
          { title: "SHP", value: "SHP" },
          { title: "WST", value: "WST" },
          { title: "STN", value: "STN" },
          { title: "SAR", value: "SAR" },
          { title: "RSD", value: "RSD" },
          { title: "SCR", value: "SCR" },
          { title: "SLL", value: "SLL" },
          { title: "SGD", value: "SGD" },
          { title: "XSU", value: "XSU" },
          { title: "SBD", value: "SBD" },
          { title: "SOS", value: "SOS" },
          { title: "SSP", value: "SSP" },
          { title: "LKR", value: "LKR" },
          { title: "SDG", value: "SDG" },
          { title: "SRD", value: "SRD" },
          { title: "SZL", value: "SZL" },
          { title: "SEK", value: "SEK" },
          { title: "CHE", value: "CHE" },
          { title: "CHW", value: "CHW" },
          { title: "SYP", value: "SYP" },
          { title: "TWD", value: "TWD" },
          { title: "TJS", value: "TJS" },
          { title: "TZS", value: "TZS" },
          { title: "THB", value: "THB" },
          { title: "TOP", value: "TOP" },
          { title: "TTD", value: "TTD" },
          { title: "TND", value: "TND" },
          { title: "TRY", value: "TRY" },
          { title: "TMT", value: "TMT" },
          { title: "UGX", value: "UGX" },
          { title: "UAH", value: "UAH" },
          { title: "AED", value: "AED" },
          { title: "USN", value: "USN" },
          { title: "UYU", value: "UYU" },
          { title: "UYI", value: "UYI" },
          { title: "UYW", value: "UYW" },
          { title: "UZS", value: "UZS" },
          { title: "VUV", value: "VUV" },
          { title: "VES", value: "VES" },
          { title: "VND", value: "VND" },
          { title: "YER", value: "YER" },
          { title: "ZMW", value: "ZMW" },
          { title: "ZWL", value: "ZWL" },
          { title: "XBA", value: "XBA" },
          { title: "XBB", value: "XBB" },
          { title: "XBC", value: "XBC" },
          { title: "XBD", value: "XBD" },
          { title: "XTS", value: "XTS" },
          { title: "XXX", value: "XXX" },
          { title: "XAU", value: "XAU" },
          { title: "XPD", value: "XPD" },
          { title: "XPT", value: "XPT" },
          { title: "XAG", value: "XAG" }
        ],
        layout: "dropdown"
      },
      validation: (Rule) => Rule.required(),
      initialValue: "USD"
    },
    {
      name: "email",
      type: "string",
      title: "Email",
      description: "A contact email for this sale",
      validation: (Rule) =>
        Rule.required().regex(
          /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/,
          {
            name: "email", // Error message is "Does not match email-pattern"
            invert: false // Boolean to allow any value that does NOT match pattern
          }
        )
    },
    {
      name: "phone",
      type: "string",
      title: "Phone Number",
      description: "A contact phone number for this sale"
    }
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "description",
      media: "logo"
    }
  }
}
